name: worksync
description: Attendance list with face recognition app. Copyright by Vocational School of IPB University and PT Sutrakabel Intimandiri.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  http: ^1.1.0
  get: ^4.6.5
  awesome_snackbar_content: ^0.1.3
  molten_navigationbar_flutter: ^1.0.1
  flutter_calendar_carousel: ^2.4.2
  camera: ^0.10.5+5
  tflite_flutter: ^0.9.0
  tflite_flutter_helper_plus: ^0.0.2
  google_ml_kit: ^0.7.3
  path_provider: ^2.0.15
  image: ^3.0.2
  quiver: ^3.2.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  webview_flutter: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: 
  uses-material-design: true
  assets:
  - assets/
  - assets/mobilefacenet.tflite
