name: worksync
description: Attendance list with face recognition app. Copyright by PT Sutrakabel Intimandiri and Vocational School of IPB University.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  http: ^1.1.0
  intl: ^0.18.1
  flutter_local_notifications: ^13.0.0
  awesome_snackbar_content: ^0.1.3
  molten_navigationbar_flutter: ^1.0.1
  flutter_calendar_carousel: ^2.4.2
  camera: ^0.10.5+9
  tflite_flutter: ^0.10.4
  tflite_flutter_helper_plus: ^0.0.2
  google_ml_kit: ^0.16.3
  path_provider: ^2.0.15
  image: ^3.0.2
  quiver: ^3.2.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  webview_flutter: ^2.0.12
  flutter_barcode_scanner: ^2.0.0
  dropdown_search: ^5.0.6
  tab_container: ^2.0.0
  carousel_slider: ^4.2.1
  share_plus: ^7.2.1
  excel: ^2.0.4
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  lottie: ^2.7.0
  image_picker: ^1.0.5
  dotted_border: ^2.1.0
  file_picker: ^6.1.1
  firebase_core: ^2.25.3
  firebase_storage: ^11.6.4
  cloud_firestore: ^4.13.6
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/mobilefacenet.tflite
    - assets/worksync.png
